import { defineConfig } from "vite-plus";

export default defineConfig({
  fmt: {
    ignorePatterns: [
      "target/**",
      "artifacts/**",
      "**/dist/**",
      ".agents/**",
      "plugin/permissions/autogenerated/**",
      "plugin/permissions/schemas/**",
      "fixtures/basic/src-tauri/gen/**",
    ],
  },
  test: { include: ["server/src/**/*.test.ts", "instrumentation/src/**/*.test.ts"] },
  pack: [
    {
      entry: ["server/src/index.ts"],
      outDir: "server/dist",
      format: "esm",
      dts: false,
      deps: { neverBundle: [/^@modelcontextprotocol\//, "zod"] },
      outExtensions: () => ({ js: ".js" }),
    },
    {
      entry: ["instrumentation/src/index.ts"],
      outDir: "instrumentation/dist",
      format: "esm",
      dts: true,
      deps: { neverBundle: [/^@tauri-apps\/api/] },
      outExtensions: () => ({ js: ".js", dts: ".d.ts" }),
    },
  ],
  lint: {
    ignorePatterns: [
      "target/**",
      "artifacts/**",
      "**/dist/**",
      ".agents/**",
      "fixtures/basic/src-tauri/gen/**",
    ],
    jsPlugins: [{ name: "vite-plus", specifier: "vite-plus/oxlint-plugin" }],
    rules: { "vite-plus/prefer-vite-plus-imports": "error" },
    options: { typeAware: true, typeCheck: true },
  },
});
